spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 916067
    url : jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
server:
  port: 8081
env:
  test2
girl:
  name : lili
  age : 19
